token: eyJ1dWlkIjoiNmUzYzZkNzQtNjYxMS00Zjc1LTkxMGEtY2FjMWJlMmRkMjA2Iiwia2luZCI6InNraWxsIiwidHlwZSI6Im9iamVjdGl2ZSJ9

# This section is used to configure this objective on Newline.
# `token` can not be changed; however, the rest of the
# information can be edited as needed. Changes you make
# here will overwrite the existing configuration on Newline
# when this catalog is published, or when using `newline objective publish`.
#
# This objective is SKILL.
# It isn't possible to change an "enabling" objective into
# a "terminal" objective, or vice versa, once it's been created.

# Everything below this line can be edited.
version: 0.0.0
title: >-
  Test actions and reducers with jest
duration: >-
  45

# `category` can only be one of the following:
# - skill
# - knowledge
# - affect
category: >-
  skill
